dist: trusty
language: java

script: ./gradlew clean integrationTest

jdk:
  - oraclejdk8
  - openjdk8

services:
  - docker

before_install:
  - docker pull mbabineau/zookeeper-exhibitor:latest
  - docker run -d -p 127.0.0.1:8181:8181 -e HOSTNAME=localhost